_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "DiveSeg_Backbone"
  DIVESEG:
    FINETUNE: False
    NAME: 'vitl'
    VIT_WEIGHT: "./checkpoints/dinov2_vitl14_pretrain.pth"
    FREEZE_VIT: True
  PIXEL_MEAN: [81.022, 113.771, 117.232]
  PIXEL_STD: [60.591, 58.505, 62.858]
OUTPUT_DIR: "./out_put/USIS10K_I_L"